kernel: hook: rename syscall_fn_t to ksu_syscall_fn_t
in kernels that have syscall_fn_t, syscall_fn_t will cause compilation errors:

../drivers/kernelsu/hook/syscall_table_hook.c:39:16: error: redefinition of typedef 'syscall_fn_t' is a C11 feature [-Werror,-Wtypedef-redefinition]
typedef long (*syscall_fn_t)(const struct pt_regs *regs);
               ^
../arch/arm64/include/asm/syscall.h:12:16: note: previous definition is here
typedef long (*syscall_fn_t)(const struct pt_regs *regs);
               ^
1 error generated.
make[3]: *** [../scripts/Makefile.build:288: drivers/kernelsu/hook/syscall_table_hook.o] Error 1
make[2]: *** [../scripts/Makefile.build:560: drivers/kernelsu] Error 2